### ISSUE TITLE
Add more datasets

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/datasets#5]
We have the possibility to add the following datasets: 

- Video games: https://codesandbox.io/s/ms-vue-is-1d6bi?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue:0-19

- Board games: https://codesandbox.io/s/meilisearch-boardgames-uj2tr 225MB

We should keep in mind the default payload size limit is 100Mb -> https://docs.meilisearch.com/reference/features/known_limitations.html#other-limitations

**Comment by curquiza** [comment]
Steam video games will be added with https://github.com/meilisearch/datasets/pull/7

**Comment by alallema** [comment]
Thanks to @shivaylamba who also think adding this one #17.

**Comment by bidoubiwa** [comment]
Board games will not be added as the dataset is bigger than the maximum file size accepted by `github`. We may consider a way to provide it remotely but meanwhile it will not be in this repo!

**Comment by bidoubiwa** [comment]
I'm closing this as the issue does not have any use any more. Keeping #17 until noble prizes have been added.
